### ISSUE TITLE
issue with sorting and different values

### ISSUE THREAD

**Issue by moocunsw** [moocunsw/PVCE-QILT#2]
The scores for a given program (e.g. 3435, Psych Science) seem to vary by virtue of how I look at them in the dashboard. 

For example if I compare SES by program for overall satisfaction and sort by SES2016, then the 2015 score for 3435 is 93.33, and the 2016 score is 90.22. If I simply then re-sort by SES2015, then the 2015 score is 75.68 and the 2016 one is again 90.22.

**Comment by whyes** [comment]
fixed in commit: https://github.com/moocunsw/PVCE-QILT/commit/90f3e8a8c662d66e7f5efa5b34db361402aa9d74
