### ISSUE TITLE
add 'comments explorer' section

### ISSUE THREAD

**Issue by moocunsw** [moocunsw/PVCE-QILT#4]
ideally this would mirror the comments section in myExperience, however as a start, create a table that can be filtered by programs (and possibly gives some overall sentiment by home/international and gender across faculties).

i realised that without enough knowledge of the db it would be quite hard to create the query for the dataset.
this is now available under the tpdata folder as rds, so this issue can be moved along

**Comment by moocunsw** [comment]
just in case, here is the query

`SELECT
SES_sample_2015_datasets.SESID,
SES_verbatim.`YEAR`,
SES_verbatim.BA,
SES_verbatim.NI,
SES_verbatim.BARAW,
SES_verbatim.NIRAW,
SES_sample_2015_datasets.E315,
SES_sample_2015_datasets.E358,
IF(SES_sample_2015_datasets.E358 > 2,'T','F') as 'INTERN',
SES_sample_2015_datasets.E307,
SES_sample_2015_datasets.E308,
SES_sample_2015_datasets.Faculty,
SES_sample_2015_datasets.AREA45 as 'AREA1'
FROM
SES_verbatim
INNER JOIN SES_sample_2015_datasets ON SES_sample_2015_datasets.SESID = SES_verbatim.SESID

UNION

SELECT
SES_population_2016_datasets.SESID,
SES_verbatim.`YEAR`,
SES_verbatim.BA,
SES_verbatim.NI,
SES_verbatim.BARAW,
SES_verbatim.NIRAW,
SES_population_2016_datasets.E315,
SES_population_2016_datasets.E358,
IF(SES_population_2016_datasets.E358 > 2,'T','F') as 'INTERN',
SES_population_2016_datasets.E307,
SES_population_2016_datasets.E308,
SES_population_2016_datasets.Faculty,
SES_population_2016_datasets.AREA1
FROM
SES_population_2016_datasets
INNER JOIN SES_verbatim ON SES_population_2016_datasets.SESID = SES_verbatim.SESID;
`

**Comment by moocunsw** [comment]
@whyes we need to add the comment downloader facility (see separate app) to the dashboard alpha.

**Comment by whyes** [comment]
@moocunsw downloader section has been added as per https://github.com/moocunsw/PVCE-QILT/commit/0424a4c6b3b6552759afe05ba0508aef12add5cb
